apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rancher-saddle.fullname" . }}-nginx
  labels:
    {{- include "rancher-saddle.labels" . | nindent 4 }}
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80;
        server_name _;

        location ^~ /_saddle/ {
            alias /usr/share/nginx/saddle/;
            expires 1h;
            add_header Cache-Control "public";
        }

        location / {
            proxy_pass {{ .Values.upstream.url | trimSuffix "/" }};
            proxy_redirect {{ .Values.upstream.url | trimSuffix "/" }} /;
            proxy_redirect default;
            proxy_cookie_domain $proxy_host $host;
            proxy_ssl_verify {{ if .Values.upstream.tlsVerify }}on{{ else }}off{{ end }};
            proxy_ssl_server_name on;

            proxy_http_version 1.1;
            proxy_set_header Host             $proxy_host;
            proxy_set_header X-Real-IP        $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_set_header Origin {{ .Values.upstream.url | trimSuffix "/" }};

            proxy_set_header Upgrade    $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600s;

            proxy_set_header Accept-Encoding "";
            gunzip on;

            proxy_hide_header Content-Security-Policy;

            sub_filter '</head>' '<link rel="stylesheet" href="/_saddle/mobile.css"><script src="/_saddle/mobile.js" defer></script></head>';
            sub_filter_once on;
        }
    }
